apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermit.fullname" . }}-tokens
  labels:
    {{- include "hermit.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.githubRwToken.token }}
  HERMIT_GITHUB_TOKEN: {{ .Values.githubRwToken.token | quote }}
  {{- end }}
  {{- if .Values.githubRwToken.orgs }}
  HERMIT_GITHUB_TOKEN_MAP: {{ .Values.githubRwToken.orgs | toJson | quote }}
  {{- end }}
  {{- if .Values.gitlabRwToken.token }}
  HERMIT_GITLAB_TOKEN: {{ .Values.gitlabRwToken.token | quote }}
  {{- end }}
  {{- if .Values.gitReadToken.token }}
  HERMIT_GIT_READ_TOKEN: {{ .Values.gitReadToken.token | quote }}
  {{- end }}
  {{- if .Values.gitReadToken.orgs }}
  HERMIT_GIT_READ_TOKEN_MAP: {{ .Values.gitReadToken.orgs | toJson | quote }}
  {{- end }}
