apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.config.serviceAccountName }}
  labels:
    {{- include "hermit.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.config.podServiceAccount }}
  labels:
    {{- include "hermit.labels" . | nindent 4 }}
